name: Test FTP Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        protocol: [ftp, ftps, sftp]
        port: [21, 22, 990]

    steps:
      - name: Trying ${{ matrix.protocol }} on port ${{ matrix.port }}
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ${{ matrix.protocol }}
          port: ${{ matrix.port }}
          local-dir: ./
          dangerous-clean-slate: false
          timeout: 120
