name: Deploy to Server via SFTP

on:
  push:
    branches:
      - main  # הסניף שממנו נעשה הדיפליי

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SFTP Deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FTP_SERVER }}          # כתובת השרת שלך
          username: ${{ secrets.FTP_USERNAME }}    # שם משתמש SSH/SFTP
          password: ${{ secrets.FTP_PASSWORD }}    # סיסמה
          port: 22                                  # פורט SFTP (22 בדרך כלל)
          source: "./*"                             # כל הקבצים בתיקיית השורש של הפרויקט
          target: "/domains/zefetbtnufa.com/public_html/"  # תיקיית היעד בשרת
          rm: false                                 # אם true, מוחק קבצים שלא נמצאים במקור
          recursive: true                           # להעלות תיקיות באופן רקורסיבי
